name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }} # 👈 Pakai SSH Key yang sama dengan FE
          port: 22
          script: |
            # 1. Masuk ke folder repo backend yang bener di VPS
            cd ~/jimpitan/jimpitan-backend || exit
            git pull origin main

            # 2. Masuk ke folder utama jimpitan untuk nembak docker-compose
            cd ~/jimpitan
            docker compose down backend
            docker compose build --no-cache backend
            docker compose up -d backend

            # 3. Bersihkan sisa-sisa image lama biar space VPS aman
            docker image prune -f
